service: aws-lambda
frameworkVersion: ">=1.2.0 <2.0.0"
plugins:
  - serverless-pseudo-parameters

custom:
  configFile: ${file(config.yml)}

provider:
  name: aws
  stage: ${self:custom.configFile.stage}
  variant: ${self:custom.configFile.variant}
  runtime: java8
  region: ${self:custom.configFile.region}
  timeout: 30 # The default is 6 seconds. Note: API Gateway current maximum is 30 seconds
  memorySize: 1024 # Overwrite the default memory size. Default is 1024. Increase by 64.
  deploymentBucket: ${self:custom.configFile.deploymentBucket}
  environment: ${file(config.yml)}
  stackName: ${self:provider.stage}-${self:provider.variant}-${self:service}
  versionFunctions: ${self:custom.configFile.versionFunctions}

package:
  artifact: target/aws-lambda.jar

functions:
  LambdaProxyHandler:
    # name must have length less than or equal to 64
    name: ${self:provider.stage}-${self:provider.variant}-LambdaProxyHandler
    handler: com.jessica.aws.lambda.LambdaProxyHandler
    role: arn:aws:iam::#{AWS::AccountId}:role/AdminRole
    events:
      - http:
          path: /hello
          method: POST